# 사용할 오픈JDK 버전을 명시적으로 지정 (예: 17.0.2)
FROM docker.io/openjdk@sha256:a996cdcc040704ec6badaf5fecf1e144c096e00231a29188596c784bcf858d05

# 작업 디렉터리 설정
WORKDIR /x-front-server

# Jenkins 빌드 결과로 생성된 JAR 파일을 컨테이너로 복사
# (아래 예시 이름을 빌드 산출물의 실제 JAR 이름에 맞게 바꿔주세요)
COPY build/libs/X-FrontServer-0.0.1-SNAPSHOT.jar /x-front-server/front.jar

# 컨테이너가 사용하는 포트 문서화 (예시 8080)
EXPOSE 8080

# 컨테이너 실행 시 JAR 실행
ENTRYPOINT ["java", "-jar", "front.jar"]