replicaCount: 3

image:
  repository: docker.io/toolod/x-timeline-api-server
  tag: 1.0.0-20250420-def456

service:
  name: x-timeline
  port: 80
  targetPort: 8080
  type: LoadBalancer

ingress:
  enabled: true
  host: x-timeline.example.com
  path: /
